#ifndef __Custom_Config_H_
#define __Custom_Config_H_

// Local OGRE 1.10 build settings shim used so EXU can compile against the
// public Ogre headers that match the Battlezone runtime DLLs.

#define OGRE_BUILD_RENDERSYSTEM_D3D9
#define OGRE_BUILD_COMPONENT_OVERLAY

#define OGRE_CONFIG_LITTLE_ENDIAN

#define OGRE_DOUBLE_PRECISION 0
#define OGRE_NODE_INHERIT_TRANSFORM 1

#define OGRE_MEMORY_ALLOCATOR 1
#define OGRE_CONTAINERS_USE_CUSTOM_MEMORY_ALLOCATOR 0
#define OGRE_STRING_USE_CUSTOM_MEMORY_ALLOCATOR 0

#define OGRE_MEMORY_TRACKER_DEBUG_MODE 0
#define OGRE_MEMORY_TRACKER_RELEASE_MODE 0
#define OGRE_ASSERT_MODE 0

#define OGRE_THREAD_SUPPORT 0
#define OGRE_THREAD_PROVIDER 0

#define OGRE_NO_MESHLOD 0
#define OGRE_NO_FREEIMAGE 0
#define OGRE_NO_DDS_CODEC 0
#define OGRE_NO_PVRTC_CODEC 1
#define OGRE_NO_ETC_CODEC 1
#define OGRE_NO_STBI_CODEC 0
#define OGRE_NO_ZIP_ARCHIVE 0
#define OGRE_NO_VIEWPORT_ORIENTATIONMODE 0
#define OGRE_NO_GLES2_CG_SUPPORT 1
#define OGRE_NO_GLES2_GLSL_OPTIMISER 1
#define OGRE_NO_GL_STATE_CACHE_SUPPORT 0
#define OGRE_NO_GLES3_SUPPORT 1
#define OGRE_NO_TBB_SCHEDULER 1
#define OGRE_USE_BOOST 0
#define OGRE_PROFILING 0
#define OGRE_NO_QUAD_BUFFER_STEREO 1
#define OGRE_BITES_HAVE_SDL 0

#endif
